### ISSUE TITLE
无法直接创建 .swift

### ISSUE THREAD

**Issue by JxJPu9bD** [QMUI/QMUI_iOS_Templates#3]
您好,我在使用模版创建文件时发现无法直接创建swift文件,可否如Xcode一般增加一个Lang的选项
![image](https://user-images.githubusercontent.com/12554248/53696795-7d551f80-3e05-11e9-9bda-d17699ea7ee8.png)
![image](https://user-images.githubusercontent.com/12554248/53696798-8ba33b80-3e05-11e9-99ed-d741858c43f6.png)

**Comment by MoLice** [comment]
QMUI 目前仍以 Objective-C 编写，所以 Template 也未提供 Swift 版本，有兴趣的话也可以提 PR 增加 Swift 版本的模板。
